name: "Setup Env"
description: "Cache apt and install required packages"
runs:
  using: "composite"
  steps:
    - name: Cache APT packages
      uses: actions/cache@v4
      with:
        path: |
          /var/cache/apt
          /var/lib/apt/lists
        key: ${{ runner.os }}-apt-${{ hashFiles('initRepo/.environment') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - run: sudo apt-get update
      shell: bash
